name: Build and tests

on:
  pull_request:
    paths:
      - '**.rs'
  push:
    paths:
      - '**.rs'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build
      - name: Run lint
        run: cargo clippy
      - name: Run tests
        run: cargo test tests
      - name: Run profiling
        run: RUST_TEST_THREADS=1 cargo test profiling
